apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: devquote
  labels:
    app: prometheus
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: prometheus
